# Generated by Django 5.2 on 2025-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_year_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('coupe', 'Купе'), ('hatchback', 'Хэтчбек'), ('convertible', 'Кабриолет'), ('pickup', 'Пикап'), ('sport', 'Спортивный')], default='sedan', max_length=20),
        ),
    ]
