# Generated by Django 5.2 on 2025-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Доступен', 'Доступен'), ('Недоступен', 'Недоступен')], default='Доступен', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='unavailable_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
